@startuml

entity "Salle" as salle {
  nom : VARCHAR
  ville : VARCHAR
  capacite : INT
}

entity "Spectacle" as spectacle {
  titre : VARCHAR
  date_evenement : DATE
  id_salle : INT
  categorie : VARCHAR
  prix : DECIMAL
}

entity "Client" as client {
  prenom : VARCHAR
  nom : VARCHAR
  email : VARCHAR
  ville : VARCHAR
}

entity "Billet" as billet {
  id_spectacle : INT
  id_client : INT
  date_achat : DATE
  place : VARCHAR
  statut : VARCHAR
  prix_paye : DECIMAL
}

salle "1" ||--o{ "*" spectacle
spectacle "1" ||--o{ "*" billet
client "1" ||--o{ "*" billet

@enduml
